name: MassMailingPaaSOnPremConnector .NETFramework Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: MassMailingPaaSOnPremConnector.sln
    steps:

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
    
    - name: Build Solution
      run: |
        msbuild.exe $env:Solution_Name /p:platform="Any CPU" /p:configuration="Release"
