name: MassMailingPaaSOnPremConnector .NETFramework Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: MassMailingPaaSOnPremConnector.sln
    steps:

    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
    
    - name: Build Solution
      run: |
        msbuild.exe $env:Solution_Name /p:platform="Any CPU" /p:configuration="Release"
